# Conexión a la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/tfg 
spring.datasource.username=root
spring.datasource.password=root12345
spring.jpa.hibernate.ddl-auto=update

# Configuración del servidor para que sea accesible desde otras máquinas en la red local


